version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: fx_deal_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
